name: Android CI

on:
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build App with Gradle
        run: ./gradlew assembleDebug
      - name: Testing fudi-permission
        run: ./gradlew assembleDebug lint testDebugUnitTest -p fudi-permission
      - name: Upload Testing fudi-permission
        uses: actions/upload-artifact@v1
        with:
          name: fudi-permission-test
          path: fudi-permission/build/reports/tests/testDebugUnitTest
      - name: Upload fudi-permission artifact
        uses: actions/upload-artifact@v1
        with:
          name: fudi-permission-aar
          path: fudi-permission/build/outputs/aar/fudi-permission-debug.aar
      - name: Testing fudi-permission-kotlin
        run: ./gradlew assembleDebug lint testDebugUnitTest -p fudi-permission-kotlin
      - name: Upload Testing fudi-permissionkotlin
        uses: actions/upload-artifact@v1
        with:
          name: fudi-permission-kotlin-test
          path: fudi-permission-kotlin/build/reports/tests/testDebugUnitTest
      - name: Upload fudi-permission-kotlin artifact
        uses: actions/upload-artifact@v1
        with:
          name: fudi-permission-kotlin-aar
          path: fudi-permission-kotlin/build/outputs/aar/fudi-permission-kotlin-debug.aar
